/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import run.ClientRun;

/**
 *
 * @author admin
 */
public class MessageView extends javax.swing.JFrame {
    String userChat = "";
    /**
     * Creates new form MessageView
     */
    public MessageView() {
        initComponents();
        
        // close window event
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (JOptionPane.showConfirmDialog(MessageView.this,
                        "Do you want to leave chat?", "Leave chat?",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                    ClientRun.socketHandler.leaveChat(userChat);
                    dispose();
                }
            }
        });
    }

    public void setInfoUserChat (String username) {
        userChat = username;
        infoUserChat.setText("Chat with: " + username);
    }
    
    public void setContentChat (String chat) {
        contentChat.append(chat);
    }
    
    public void eventSendMessage () {
        String message = tfMessage.getText().trim();
        if (message.equals("")) {
            tfMessage.grabFocus();
        } else {
            ClientRun.socketHandler.sendMessage(userChat, message);
            tfMessage.setText("");
            tfMessage.grabFocus();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentChat = new javax.swing.JTextArea();
        infoUserChat = new javax.swing.JLabel();
        btnLeaveChat = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfMessage.setBackground(new java.awt.Color(255, 224, 186));
        tfMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMessageKeyPressed(evt);
            }
        });
        getContentPane().add(tfMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 311, 311, 38));

        btnSend.setBackground(new java.awt.Color(153, 0, 0));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 312, 112, 38));

        contentChat.setEditable(false);
        contentChat.setBackground(new java.awt.Color(255, 235, 235));
        contentChat.setColumns(20);
        contentChat.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        contentChat.setRows(5);
        jScrollPane1.setViewportView(contentChat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 441, 213));

        infoUserChat.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        infoUserChat.setForeground(new java.awt.Color(255, 255, 255));
        infoUserChat.setText("Chat with:");
        getContentPane().add(infoUserChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 26, 290, 36));

        btnLeaveChat.setBackground(new java.awt.Color(153, 0, 0));
        btnLeaveChat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLeaveChat.setForeground(new java.awt.Color(204, 255, 255));
        btnLeaveChat.setText("Leave chat");
        btnLeaveChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveChatActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeaveChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 26, 120, 36));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Emerald Sky (1).jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -4, 480, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaveChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveChatActionPerformed
        ClientRun.socketHandler.leaveChat(userChat);
        dispose();
    }//GEN-LAST:event_btnLeaveChatActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        eventSendMessage();
    }//GEN-LAST:event_btnSendActionPerformed

    private void tfMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMessageKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            eventSendMessage();
        }
    }//GEN-LAST:event_tfMessageKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLeaveChat;
    private javax.swing.JButton btnSend;
    private javax.swing.JTextArea contentChat;
    private javax.swing.JLabel infoUserChat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfMessage;
    // End of variables declaration//GEN-END:variables
}
