/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package view;

/**
 *
 * @author nguye
 */
public class NewCustomizer extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer NewCustomizer
     */
    public NewCustomizer() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane4 = new javax.swing.JLayeredPane();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();

        setLayout(new java.awt.BorderLayout());

        label1.setBackground(new java.awt.Color(255, 0, 0));
        label1.setText("label1");
        jLayeredPane4.add(label1);
        label1.setBounds(60, 90, 150, 110);

        label2.setBackground(new java.awt.Color(102, 102, 255));
        label2.setText("label2");
        jLayeredPane4.add(label2);
        label2.setBounds(120, 110, 130, 100);

        add(jLayeredPane4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
